# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'devcodequality'
    scannerMode: 'MSBuild'
    projectKey: 'devcodequality'
  displayName: 'Prepare sonar cloud'

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

